### ISSUE TITLE
Extraction: generalize parsing of coordinate files

### ISSUE THREAD

**Issue by axelbrunger** [brungerlab/pycresta#13]
Current the code assumes the coords file is an integer with a single space between coordinate points (i.e. "int1 int2 int3"). 
This isn't the default output of IMOD model2point - at least my version - which defaults to float and 
tab separated values ("    float1    float2    float3"). Comma separated values also fail for the same reason since the string cannot be converted to int. Please implement auto-detect format: convert floats to an integer, and handle separators other than single spaces (any number of spaces or other delimiters).

**Comment by mldylai** [comment]
I changed the code so that it handles separators including one or more spaces, tabs, commas, periods, colons, and semi-colons. However, I can't test if the code works because extraction requires a tomogram, so let me know if I need to fix anything or if there are any more characters you want to include, thanks!

**Comment by axelbrunger** [comment]
Thank you so much. I tested it with multiple spaces, commas, and floats. It works well. Best, Axel
